name: iot_app
description: "An Android App that allows to control an ESP32 board using Bluetooth"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  syncfusion_flutter_gauges: ^26.1.42
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

